### ISSUE TITLE
JVM crash when running two apps that use sigar-loader

### ISSUE THREAD

**Issue by 2m** [kamon-io/sigar-loader#6]
When starting second instance of an application that uses sigar-loader, first instance crashes. This, however does not happen when using sigar library directly.

I have created a small reproducer:
- [uses sigar-loader](https://github.com/2m/sigar-loader-multi-jvm) and crashes
- [uses sigar library](https://github.com/2m/sigar-loader-multi-jvm/tree/sigar-library) and works

A workaround is to provide a different per-jvm-path for sigar-loader for native library extraction. However it would be great to understand and fix the underlying problem.

**Comment by Andrei-Pozolotin** [comment]
1) it is documented in the examples:
https://github.com/akka/akka/blob/master/akka-samples/akka-sample-cluster-scala/src/main/resources/application.conf#L36

2) it is used in the tests:
https://github.com/akka/akka/blob/master/akka-cluster-metrics/src/multi-jvm/scala/akka/cluster/metrics/ClusterMetricsExtensionSpec.scala#L28

3) the underlying reason is os-level library loading locking behavior interferes with jvm library loading locking behavior

4) yes, it is possible to delve deeper and work around this condition, but from the "normal usage" perspective we are better off just to document this case better, instead of more JNI hacking

**Comment by 2m** [comment]
Fair enough. I will add a mention of this caveat to the Cluster Metrics Extension Akka documentation page then so it is more visible to the users.

**Comment by Andrei-Pozolotin** [comment]
thank you. documented:
https://github.com/kamon-io/sigar-loader/blob/master/core/src/main/resources/README.md#provision-from-several-jvm
